version: "3.9"

services:
  database:
    image: postgres:latest
    volumes:
      - drf-redbox:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

volumes:
  drf-redbox:
